version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    volumes:
    - .:/var/www
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  server:
    image: nginx
    ports:
    - 8090:80
    - 8095:443
    volumes:
    - ./:/var/www
    - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8092:8080

networks:
  app-network:
    driver: bridge

